### PR TITLE
Penalise Unrealistic Gametime

### PR DESCRIPTION
**Pull request by rubenwardy**

### CODE REVIEW

**Comment by rubenwardy** [comment]
Currently this only cancels the game_time points - maybe it should take more away as well?

**Comment by ShadowNinja** [comment]
There are some problems with this:
  * This is hacky (obviously).
  * If you're really trying to game the server list you can just set your `game_time` to a few seconds less than the cutoff.

**Comment by rubenwardy** [comment]
2: If you knew the algorithm of the server list well enough, you'd just put the game_time at +8 months.

Ideally the master server would validate game times by looking at when the server first came online. Unfortunately this is not possible as the server may have been alive before it was upgraded to a version which supports the server list. The pull request penalises times which are obviously wrong, rather than times which are incorrect.

**Comment by nerzhul** [comment]
i agree with @rubenwardy this can be a good idea to penalize > 4 years old time servers

**Comment by est31** [comment]
I agree with @rubenwardy  too.

**Comment by rubenwardy** [comment]
Closing as not really wanted, it seems

**Pull request closed without merging**
